//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChromeCast.Desktop.AudioStreamer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChromeCast.Desktop.AudioStreamer.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering.
        /// </summary>
        internal static string Buffering {
            get {
                return ResourceManager.GetString("Buffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log.
        /// </summary>
        internal static string Button_ClearLog_Text {
            get {
                return ResourceManager.GetString("Button_ClearLog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string Button_ClipboardCopy_Text {
            get {
                return ResourceManager.GetString("Button_ClipboardCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Button_Down_Text {
            get {
                return ResourceManager.GetString("Button_Down_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string Button_Mute_Text {
            get {
                return ResourceManager.GetString("Button_Mute_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        internal static string Button_ResetSetting_Text {
            get {
                return ResourceManager.GetString("Button_ResetSetting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan again for devices.
        /// </summary>
        internal static string Button_ScanAgain_Text {
            get {
                return ResourceManager.GetString("Button_ScanAgain_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Devices.
        /// </summary>
        internal static string Button_SyncDevices_Text {
            get {
                return ResourceManager.GetString("Button_SyncDevices_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Button_Up_Text {
            get {
                return ResourceManager.GetString("Button_Up_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically restart when the stream is closed.
        /// </summary>
        internal static string Check_AutomaticallyRestart_Text {
            get {
                return ResourceManager.GetString("Check_AutomaticallyRestart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically start devices at startup.
        /// </summary>
        internal static string Check_AutomaticallyStart_Text {
            get {
                return ResourceManager.GetString("Check_AutomaticallyStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Keyboard shortcuts: Up = Ctrl+Alt+U; Down = Ctrl+Alt+D; (Un)Mute = Ctrl+Alt+M.
        /// </summary>
        internal static string Check_KeyboardShortcuts_Text {
            get {
                return ResourceManager.GetString("Check_KeyboardShortcuts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log device communication.
        /// </summary>
        internal static string Check_LogDeviceCommunication_Text {
            get {
                return ResourceManager.GetString("Check_LogDeviceCommunication_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lag control (experimental).
        /// </summary>
        internal static string Check_ShowLagControl_Text {
            get {
                return ResourceManager.GetString("Check_ShowLagControl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window at startup.
        /// </summary>
        internal static string Check_ShowWindowOnStart_Text {
            get {
                return ResourceManager.GetString("Check_ShowWindowOnStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Stream.
        /// </summary>
        internal static string ChromeCast_StreamTitle {
            get {
                return ResourceManager.GetString("ChromeCast_StreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Error.
        /// </summary>
        internal static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposed.
        /// </summary>
        internal static string Disposed {
            get {
                return ResourceManager.GetString("Disposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices (click name to start streaming).
        /// </summary>
        internal static string Group_Devices_Text {
            get {
                return ResourceManager.GetString("Group_Devices_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lag Control.
        /// </summary>
        internal static string Group_Lag_Text {
            get {
                return ResourceManager.GetString("Group_Lag_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Group_Options_Text {
            get {
                return ResourceManager.GetString("Group_Options_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume all devices:.
        /// </summary>
        internal static string Group_VolumeAllDevices_Text {
            get {
                return ResourceManager.GetString("Group_VolumeAllDevices_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        internal static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP4 address used:.
        /// </summary>
        internal static string Label_IPAddressUsed_Text {
            get {
                return ResourceManager.GetString("Label_IPAddressUsed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest keep-alive message:.
        /// </summary>
        internal static string Label_KeepAlive_Text {
            get {
                return ResourceManager.GetString("Label_KeepAlive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental feature: Try to keep the buffer on the device as small as possible without hearing gaps..
        /// </summary>
        internal static string Label_LagExperimental_Text {
            get {
                return ResourceManager.GetString("Label_LagExperimental_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Label_Language_Text {
            get {
                return ResourceManager.GetString("Label_Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum lag / best quality.
        /// </summary>
        internal static string Label_MaximumLag_Text {
            get {
                return ResourceManager.GetString("Label_MaximumLag_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum lag / poor quality.
        /// </summary>
        internal static string Label_MinimumLag_Text {
            get {
                return ResourceManager.GetString("Label_MinimumLag_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording device:.
        /// </summary>
        internal static string Label_RecordingDevice_Text {
            get {
                return ResourceManager.GetString("Label_RecordingDevice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream format.
        /// </summary>
        internal static string Label_StreamFormat_Text {
            get {
                return ResourceManager.GetString("Label_StreamFormat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mp3 formats have a long lag and buffering time..
        /// </summary>
        internal static string Label_StreamFormatExtra_Text {
            get {
                return ResourceManager.GetString("Label_StreamFormatExtra_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string Language_French {
            get {
                return ResourceManager.GetString("Language_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launched Application.
        /// </summary>
        internal static string LaunchedApplication {
            get {
                return ResourceManager.GetString("LaunchedApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching Application.
        /// </summary>
        internal static string LaunchingApplication {
            get {
                return ResourceManager.GetString("LaunchingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Cancelled.
        /// </summary>
        internal static string LoadCancelled {
            get {
                return ResourceManager.GetString("LoadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Failed.
        /// </summary>
        internal static string LoadFailed {
            get {
                return ResourceManager.GetString("LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Media.
        /// </summary>
        internal static string LoadingMedia {
            get {
                return ResourceManager.GetString("LoadingMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out.
        /// </summary>
        internal static string Log_Out {
            get {
                return ResourceManager.GetString("Log_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChromeCast Desktop Audio Streamer.
        /// </summary>
        internal static string MainForm_Text {
            get {
                return ResourceManager.GetString("MainForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recording devices found..
        /// </summary>
        internal static string MessageBox_NoRecordingDevices {
            get {
                return ResourceManager.GetString("MessageBox_NoRecordingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mp3 (128 kbps).
        /// </summary>
        internal static string Mp3_128 {
            get {
                return ResourceManager.GetString("Mp3_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mp3 (320 kbps).
        /// </summary>
        internal static string Mp3_320 {
            get {
                return ResourceManager.GetString("Mp3_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Tab_Log_Text {
            get {
                return ResourceManager.GetString("Tab_Log_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Tab_Options_Text {
            get {
                return ResourceManager.GetString("Tab_Options_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string TrayIcon_Close {
            get {
                return ResourceManager.GetString("TrayIcon_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wav (44100 Hz).
        /// </summary>
        internal static string Wav {
            get {
                return ResourceManager.GetString("Wav", resourceCulture);
            }
        }
    }
}
